# Generated by Django 4.2 on 2023-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('visualizaciones', models.IntegerField(default=0)),
                ('puntaje', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('visualizaciones', models.IntegerField(default=0)),
                ('puntaje', models.FloatField(default=0)),
            ],
        ),
    ]
