# Generated by Django 4.2 on 2023-04-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cantidad_puntuaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='suma_puntajes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='cantidad_puntuaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='suma_puntajes',
            field=models.FloatField(default=0),
        ),
    ]
